In [2]:
#Q1
import numpy as np
arr= np.array([1,2,3])
print(arr+2)
print(arr*3)
print(arr/2)

[3 4 5]
[3 6 9]
[0.5 1.  1.5]


In [7]:
#Q2
arr = np.array([1, 2, 3, 4, 5])
print("reversed:",arr[::-1])
# Q2(b): Find most frequent value and indices
x= np.array([1,2,3,4,5,1,2,1,1,1])
value= np.bincount(x).argmax()
print("most frequent value:", value)
print("indices:", np.where(x==value)[0])

y = np.array([1,1,1,2,3,4,2,4,3,3])
value = np.bincount(y).argmax()
print("most frequent value:", value)
print("indices:", np.where(y == value)[0])

reversed: [5 4 3 2 1]
most frequent value: 1
indices: [0 5 7 8 9]
most frequent value: 1
indices: [0 1 2]


In [8]:
# Q3: Access elements using row and column indices

import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(arr[0,1])
print(arr[2,0])

20
70


In [9]:
# Q4: Create array using linspace and find properties
Lalramdina = np.linspace(10, 100, 25)

print("Dimensions:", Lalramdina.ndim)

print("Shape:", Lalramdina.shape)

print("Total elements:", Lalramdina.size)

print("Data type:", Lalramdina.dtype)

print("Total bytes:", Lalramdina.nbytes)


# Transpose using reshape()
transpose_array = Lalramdina.reshape(25, 1).T

print(transpose_array)

# Can we use T attribute directly?
print(Lalramdina.T)

Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200
[[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [ ]:
# Q5: Create 2D array and perform operations

import numpy as np

ucs420_Lalramdina = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])

print("Mean:", np.mean(ucs420_Lalramdina))

print("Median:", np.median(ucs420_Lalramdina))

print("Max:", np.max(ucs420_Lalramdina))

print("Min:", np.min(ucs420_Lalramdina))

print("Unique elements:", np.unique(ucs420_Lalramdina))


# Reshape to 4 rows and 3 columns

reshaped_ucs420_Lalramdina = ucs420_Lalramdina.reshape(4,3)

print(reshaped_ucs420_Lalramdina)


# Resize to 2 rows and 3 columns

resized_ucs420_Lalramdina = np.resize(ucs420_Lalramdina,(2,3))

print(resized_ucs420_Lalramdina)