In [1]:
# Q1: Sensor Readings
import numpy as np

temperature= np.array([25, 28, 31, 35, 38, 27, 33, 40])

# a. Add 2°C to every reading
temperature= temperature + 2
print(temperature)

# b. Convert Celsius to Fahrenheit
fahrenheit = (9/5)*temperature + 32
print(fahrenheit)

# c. Readings greater than 32°C
greater = temperature[temperature > 32]
print(greater)

# d. Count readings exceeding 32°C
count= np.sum(temperature > 32)
print(count)

[27 30 33 37 40 29 35 42]
[ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]
[33 37 40 35 42]
5


In [2]:
# Q2: Daily Steps
import numpy as np

steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

# a. Total steps
print(np.sum(steps))

# b. Mean steps
print(np.mean(steps))

# c. Maximum and minimum
print(np.max(steps))
print(np.min(steps))

# d. Total steps for each day
print(np.sum(steps, axis=0))

# e. Total steps for each user
print(np.sum(steps, axis=1))

# f. Position of maximum value
print(np.unravel_index(np.argmax(steps), steps.shape))

84200
7016.666666666667
9500
4500
[26500 27300 30400]
[18300 24500 14400 27000]
(np.int64(3), np.int64(2))


In [3]:
# Q3: NumPy Slicing, Copying, Reshaping
import numpy as np

# a. Create array
original = np.array([1, 2, 3, 4, 5, 6])

# b. Slice index 1 to 4
subset = original[1:5]

# c. Modify subset
subset[0] = 999
print(original)
print(subset)

# d. Create a copy and modify it
copied = original[1:5].copy()
copied[0] = 500
print(original)
print(copied)

# e. Create and reshape array
matrix = np.arange(1, 13).reshape(3, 4)
print(matrix)

# f. Indexing and slicing
print(matrix[0])        # First row
print(matrix[-1])       # Last row
print(matrix[:, 1])     # Second column
print(matrix[1:3, 2:4]) # Rows 1–2, columns 2–3

# g. Flatten using flatten() and ravel()
flat = matrix.flatten()
raveled = matrix.ravel()
print(flat)
print(raveled)

# h. Modify ravel()
raveled[0] = 100
print(matrix)

# i. Modify flatten()
flat[1] = 200
print(matrix)

# j. Display properties
print(matrix.shape)
print(matrix.ndim)
print(matrix.size)
print(matrix.dtype)

[  1 999   3   4   5   6]
[999   3   4   5]
[  1 999   3   4   5   6]
[500   3   4   5]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4]
[ 9 10 11 12]
[ 2  6 10]
[[ 7  8]
 [11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
(3, 4)
2
12
int64
